version: "3.9"

services:
  frontend:
    build:
      context: ./Home_Service_App_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fullstack-network

  backend:
    build:
      context: ./House_Service_App_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: 
      - ./House_Service_App_backend/.env  # Correct path to .env
    depends_on:
      - db
    networks:
      - fullstack-network

  db:
    image: postgres:latest
    container_name: my-project_db
    env_file: 
      - ./House_Service_App_backend/.env  # Correct path to .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fullstack-network

networks:
  fullstack-network:

volumes:
  postgres_data:
