name: Build and Deploy Backend

on:
  push:
    branches:
      - raj_dev  # Replace with your actual backend branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        env:
          AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        run: |
          # Debugging step to print AWS environment variables (excluding sensitive values)
          echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
          echo "AWS_ACCESS_KEY_ID: [REDACTED]"  # Do not print sensitive values
          
          # Log in to ECR
          echo $(aws ecr get-login-password --region eu-west-1) | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com


      # - name: Log in to Amazon ECR
      #   env:
      #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  # Reference to your secret
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Reference to your secret
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Reference to your secret
      #   run: |
      #     # Debugging step to print AWS environment variables (excluding sensitive values)
      #     echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
      #     echo "AWS_ACCESS_KEY_ID: [REDACTED]"  # Do not print sensitive values
          
      #     # Log in to ECR
      #     echo $(aws ecr get-login-password --region eu-west-1) | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t backend ./House_Service_App_backend

      - name: Push Docker image
        run: |
          docker tag backend:latest $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/backend-repo:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/backend-repo:latest
