name: Build and Deploy Backend

on:
  push:
    branches:
      - raj_dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify AWS Credentials and Region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
          AWS_SIGNATURE_VERSION: "v4"
        run: |
          aws sts get-caller-identity
          
      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: eu-west-1
        run: |
          echo "Logging into ECR..."
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com
          
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t backend ./House_Service_App_backend
          
      - name: Tag and Push Docker image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          echo "Tagging Docker image..."
          docker tag backend:latest $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/backend-repo:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/backend-repo:latest
