name: Build and Deploy Backend

on:
  push:
    branches:
      - raj_dev  # Replace with your actual backend branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  # Reference to your secret
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Reference to your secret
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Reference to your secret
        run: |
          echo "Logging into Amazon ECR..."
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com
          echo "Logged into Amazon ECR successfully.                   "

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t backend .
          echo "Docker image built successfully."

      - name: Push Docker image
        run: |
          echo "Tagging Docker image..."
           echo "AWS Account ID: $AWS_ACCOUNT_ID"
          docker tag backend:latest $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/backend-repo:latest
          echo "Pushing Docker image to ECR..."
          
          docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/backend-repo:latest
          docker push 412404422906.dkr.ecr.us-west-1.amazonaws.com/backend-repo:latest
          echo "Docker image pushed successfully."
