name: Build and Deploy Frontend

on:
  push:
    branches:
      - frontend-branch # Replace with your actual frontend branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t frontend .
          
      - name: Push Docker image
        run: |
          docker tag frontend:latest <aws_account_id>.dkr.ecr.us-west-1.amazonaws.com/frontend:latest
          docker push <aws_account_id>.dkr.ecr.us-west-1.amazonaws.com/frontend:latest
