name: Build and Deploy Frontend

on:
  push:
    branches:
      - frontend-branch # Replace with your actual frontend branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

        
      - name: Log in to Amazon ECR
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  # Reference to your secret
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Reference to your secret
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Reference to your secret
        run: |
          echo "AWS Account ID: $AWS_ACCOUNT_ID"  # Check if AWS_ACCOUNT_ID is set correctly
          echo "Logging into Amazon ECR..."
          aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com
          echo "Logged into Amazon ECR successfully."

      - name: Build Docker image
        run: |
          docker build -t frontend .

      - name: Push Docker image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  # Ensure AWS_ACCOUNT_ID is set again in this step

        run: |
          docker tag frontend:latest $AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/frontend:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-west-1.amazonaws.com/frontend:latest
